name: Generate Streak Stats

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  workflow_dispatch: # Run manually from the Actions tab
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Run any time this file is modified

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate streak.svg
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&locale=fr&mode=daily&theme=dark&hide_border=true&border_radius=5&order=3
          path: dist/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push streak stats to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}